/**
 * Full ISO 4217 currency list: code, display symbol, English name.
 *
 * GENERATED once via Node's Intl (supportedValuesOf + DisplayNames + narrowSymbol);
 * do not hand-edit entries. Kept as static data so React Native (Hermes) never
 * needs Intl.DisplayNames at runtime. Identical copies live in admin-panel/,
 * app/ and frontend/ — keep them in sync.
 */

export interface CurrencyInfo {
  code: string;
  symbol: string;
  name: string;
}

export const CURRENCIES: CurrencyInfo[] = [
  { code: "AFN", symbol: "؋", name: "Afghan Afghani" },
  { code: "ALL", symbol: "ALL", name: "Albanian Lek" },
  { code: "DZD", symbol: "DZD", name: "Algerian Dinar" },
  { code: "AOA", symbol: "Kz", name: "Angolan Kwanza" },
  { code: "ARS", symbol: "$", name: "Argentine Peso" },
  { code: "AMD", symbol: "֏", name: "Armenian Dram" },
  { code: "AWG", symbol: "AWG", name: "Aruban Florin" },
  { code: "AUD", symbol: "$", name: "Australian Dollar" },
  { code: "AZN", symbol: "₼", name: "Azerbaijani Manat" },
  { code: "BSD", symbol: "$", name: "Bahamian Dollar" },
  { code: "BHD", symbol: "BHD", name: "Bahraini Dinar" },
  { code: "BDT", symbol: "৳", name: "Bangladeshi Taka" },
  { code: "BBD", symbol: "$", name: "Barbadian Dollar" },
  { code: "BYN", symbol: "BYN", name: "Belarusian Ruble" },
  { code: "BZD", symbol: "$", name: "Belize Dollar" },
  { code: "BMD", symbol: "$", name: "Bermudan Dollar" },
  { code: "BTN", symbol: "BTN", name: "Bhutanese Ngultrum" },
  { code: "BOB", symbol: "Bs", name: "Bolivian Boliviano" },
  { code: "BAM", symbol: "KM", name: "Bosnia-Herzegovina Convertible Mark" },
  { code: "BWP", symbol: "P", name: "Botswanan Pula" },
  { code: "BRL", symbol: "R$", name: "Brazilian Real" },
  { code: "GBP", symbol: "£", name: "British Pound" },
  { code: "BND", symbol: "$", name: "Brunei Dollar" },
  { code: "BGN", symbol: "BGN", name: "Bulgarian Lev" },
  { code: "BIF", symbol: "BIF", name: "Burundian Franc" },
  { code: "KHR", symbol: "៛", name: "Cambodian Riel" },
  { code: "CAD", symbol: "$", name: "Canadian Dollar" },
  { code: "CVE", symbol: "CVE", name: "Cape Verdean Escudo" },
  { code: "XCG", symbol: "Cg.", name: "Caribbean guilder" },
  { code: "KYD", symbol: "$", name: "Cayman Islands Dollar" },
  { code: "XAF", symbol: "FCFA", name: "Central African CFA Franc" },
  { code: "XPF", symbol: "CFPF", name: "CFP Franc" },
  { code: "CLP", symbol: "$", name: "Chilean Peso" },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan" },
  { code: "COP", symbol: "$", name: "Colombian Peso" },
  { code: "KMF", symbol: "CF", name: "Comorian Franc" },
  { code: "CDF", symbol: "CDF", name: "Congolese Franc" },
  { code: "CRC", symbol: "₡", name: "Costa Rican Colón" },
  { code: "HRK", symbol: "kn", name: "Croatian Kuna" },
  { code: "CUC", symbol: "$", name: "Cuban Convertible Peso" },
  { code: "CUP", symbol: "$", name: "Cuban Peso" },
  { code: "CZK", symbol: "Kč", name: "Czech Koruna" },
  { code: "DKK", symbol: "kr", name: "Danish Krone" },
  { code: "DJF", symbol: "DJF", name: "Djiboutian Franc" },
  { code: "DOP", symbol: "$", name: "Dominican Peso" },
  { code: "XCD", symbol: "$", name: "East Caribbean Dollar" },
  { code: "EGP", symbol: "E£", name: "Egyptian Pound" },
  { code: "ERN", symbol: "ERN", name: "Eritrean Nakfa" },
  { code: "ETB", symbol: "ETB", name: "Ethiopian Birr" },
  { code: "EUR", symbol: "€", name: "Euro" },
  { code: "FKP", symbol: "£", name: "Falkland Islands Pound" },
  { code: "FJD", symbol: "$", name: "Fijian Dollar" },
  { code: "GMD", symbol: "GMD", name: "Gambian Dalasi" },
  { code: "GEL", symbol: "₾", name: "Georgian Lari" },
  { code: "GHS", symbol: "GH₵", name: "Ghanaian Cedi" },
  { code: "GIP", symbol: "£", name: "Gibraltar Pound" },
  { code: "GTQ", symbol: "Q", name: "Guatemalan Quetzal" },
  { code: "GNF", symbol: "FG", name: "Guinean Franc" },
  { code: "GYD", symbol: "$", name: "Guyanaese Dollar" },
  { code: "HTG", symbol: "HTG", name: "Haitian Gourde" },
  { code: "HNL", symbol: "L", name: "Honduran Lempira" },
  { code: "HKD", symbol: "$", name: "Hong Kong Dollar" },
  { code: "HUF", symbol: "Ft", name: "Hungarian Forint" },
  { code: "ISK", symbol: "kr", name: "Icelandic Króna" },
  { code: "INR", symbol: "₹", name: "Indian Rupee" },
  { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
  { code: "IRR", symbol: "IRR", name: "Iranian Rial" },
  { code: "IQD", symbol: "IQD", name: "Iraqi Dinar" },
  { code: "ILS", symbol: "₪", name: "Israeli New Shekel" },
  { code: "JMD", symbol: "$", name: "Jamaican Dollar" },
  { code: "JPY", symbol: "¥", name: "Japanese Yen" },
  { code: "JOD", symbol: "JOD", name: "Jordanian Dinar" },
  { code: "KZT", symbol: "₸", name: "Kazakhstani Tenge" },
  { code: "KES", symbol: "KES", name: "Kenyan Shilling" },
  { code: "KWD", symbol: "KWD", name: "Kuwaiti Dinar" },
  { code: "KGS", symbol: "⃀", name: "Kyrgystani Som" },
  { code: "LAK", symbol: "₭", name: "Laotian Kip" },
  { code: "LBP", symbol: "L£", name: "Lebanese Pound" },
  { code: "LSL", symbol: "LSL", name: "Lesotho Loti" },
  { code: "LRD", symbol: "$", name: "Liberian Dollar" },
  { code: "LYD", symbol: "LYD", name: "Libyan Dinar" },
  { code: "MOP", symbol: "MOP", name: "Macanese Pataca" },
  { code: "MKD", symbol: "MKD", name: "Macedonian Denar" },
  { code: "MGA", symbol: "Ar", name: "Malagasy Ariary" },
  { code: "MWK", symbol: "MWK", name: "Malawian Kwacha" },
  { code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
  { code: "MVR", symbol: "MVR", name: "Maldivian Rufiyaa" },
  { code: "MRU", symbol: "MRU", name: "Mauritanian Ouguiya" },
  { code: "MUR", symbol: "Rs", name: "Mauritian Rupee" },
  { code: "MXN", symbol: "$", name: "Mexican Peso" },
  { code: "MDL", symbol: "MDL", name: "Moldovan Leu" },
  { code: "MNT", symbol: "₮", name: "Mongolian Tugrik" },
  { code: "MAD", symbol: "MAD", name: "Moroccan Dirham" },
  { code: "MZN", symbol: "MZN", name: "Mozambican Metical" },
  { code: "MMK", symbol: "K", name: "Myanmar Kyat" },
  { code: "NAD", symbol: "$", name: "Namibian Dollar" },
  { code: "NPR", symbol: "Rs", name: "Nepalese Rupee" },
  { code: "ANG", symbol: "ANG", name: "Netherlands Antillean Guilder" },
  { code: "TWD", symbol: "$", name: "New Taiwan Dollar" },
  { code: "NZD", symbol: "$", name: "New Zealand Dollar" },
  { code: "NIO", symbol: "C$", name: "Nicaraguan Córdoba" },
  { code: "NGN", symbol: "₦", name: "Nigerian Naira" },
  { code: "KPW", symbol: "₩", name: "North Korean Won" },
  { code: "NOK", symbol: "kr", name: "Norwegian Krone" },
  { code: "OMR", symbol: "OMR", name: "Omani Rial" },
  { code: "PKR", symbol: "Rs", name: "Pakistani Rupee" },
  { code: "PAB", symbol: "PAB", name: "Panamanian Balboa" },
  { code: "PGK", symbol: "PGK", name: "Papua New Guinean Kina" },
  { code: "PYG", symbol: "₲", name: "Paraguayan Guarani" },
  { code: "PEN", symbol: "PEN", name: "Peruvian Sol" },
  { code: "PHP", symbol: "₱", name: "Philippine Peso" },
  { code: "PLN", symbol: "zł", name: "Polish Zloty" },
  { code: "QAR", symbol: "QAR", name: "Qatari Riyal" },
  { code: "RON", symbol: "lei", name: "Romanian Leu" },
  { code: "RUB", symbol: "₽", name: "Russian Ruble" },
  { code: "RWF", symbol: "RF", name: "Rwandan Franc" },
  { code: "SVC", symbol: "SVC", name: "Salvadoran Colón" },
  { code: "WST", symbol: "WST", name: "Samoan Tala" },
  { code: "STN", symbol: "Db", name: "São Tomé & Príncipe Dobra" },
  { code: "SAR", symbol: "SAR", name: "Saudi Riyal" },
  { code: "RSD", symbol: "RSD", name: "Serbian Dinar" },
  { code: "SCR", symbol: "SCR", name: "Seychellois Rupee" },
  { code: "SLE", symbol: "SLE", name: "Sierra Leonean Leone" },
  { code: "SLL", symbol: "SLL", name: "Sierra Leonean Leone (1964—2022)" },
  { code: "SGD", symbol: "$", name: "Singapore Dollar" },
  { code: "SBD", symbol: "$", name: "Solomon Islands Dollar" },
  { code: "SOS", symbol: "SOS", name: "Somali Shilling" },
  { code: "ZAR", symbol: "R", name: "South African Rand" },
  { code: "KRW", symbol: "₩", name: "South Korean Won" },
  { code: "SSP", symbol: "£", name: "South Sudanese Pound" },
  { code: "XDR", symbol: "XDR", name: "Special Drawing Rights" },
  { code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee" },
  { code: "SHP", symbol: "£", name: "St. Helena Pound" },
  { code: "XSU", symbol: "XSU", name: "Sucre" },
  { code: "SDG", symbol: "SDG", name: "Sudanese Pound" },
  { code: "SRD", symbol: "$", name: "Surinamese Dollar" },
  { code: "SZL", symbol: "SZL", name: "Swazi Lilangeni" },
  { code: "SEK", symbol: "kr", name: "Swedish Krona" },
  { code: "CHF", symbol: "CHF", name: "Swiss Franc" },
  { code: "SYP", symbol: "£", name: "Syrian Pound" },
  { code: "TJS", symbol: "TJS", name: "Tajikistani Somoni" },
  { code: "TZS", symbol: "TZS", name: "Tanzanian Shilling" },
  { code: "THB", symbol: "฿", name: "Thai Baht" },
  { code: "TOP", symbol: "T$", name: "Tongan Paʻanga" },
  { code: "TTD", symbol: "$", name: "Trinidad & Tobago Dollar" },
  { code: "TND", symbol: "TND", name: "Tunisian Dinar" },
  { code: "TRY", symbol: "₺", name: "Turkish Lira" },
  { code: "TMT", symbol: "TMT", name: "Turkmenistani Manat" },
  { code: "UGX", symbol: "UGX", name: "Ugandan Shilling" },
  { code: "UAH", symbol: "₴", name: "Ukrainian Hryvnia" },
  { code: "AED", symbol: "AED", name: "United Arab Emirates Dirham" },
  { code: "UYU", symbol: "$", name: "Uruguayan Peso" },
  { code: "USD", symbol: "$", name: "US Dollar" },
  { code: "UZS", symbol: "UZS", name: "Uzbekistani Som" },
  { code: "VUV", symbol: "VUV", name: "Vanuatu Vatu" },
  { code: "VES", symbol: "VES", name: "Venezuelan Bolívar" },
  { code: "VND", symbol: "₫", name: "Vietnamese Dong" },
  { code: "XOF", symbol: "F CFA", name: "West African CFA Franc" },
  { code: "YER", symbol: "YER", name: "Yemeni Rial" },
  { code: "ZMW", symbol: "ZK", name: "Zambian Kwacha" },
  { code: "ZWL", symbol: "ZWL", name: "Zimbabwean Dollar (2009–2024)" },
  { code: "ZWG", symbol: "ZWG", name: "Zimbabwean Gold" },
];

export const CURRENCY_BY_CODE: Record<string, CurrencyInfo> = Object.fromEntries(
  CURRENCIES.map((c) => [c.code, c]),
);

/** Display symbol for an ISO code; unknown codes fall back to the code itself. */
export function currencySymbol(code?: string | null): string {
  if (!code) return "₹";
  const info = CURRENCY_BY_CODE[code.toUpperCase()];
  return info ? info.symbol : `${code.toUpperCase()} `;
}
