/**
 * Timezones offered in the store form's dropdown. Static on purpose: `Intl.supportedValuesOf` can
 * differ between the server render and the browser, which would break hydration of the <select>.
 * The stored value is always kept selectable even when it is not listed (see StoreForm).
 */
export const TIMEZONE_OPTIONS: { value: string; label: string }[] = [
  { value: "America/New_York", label: "US Eastern — New York" },
  { value: "America/Chicago", label: "US Central — Chicago" },
  { value: "America/Denver", label: "US Mountain — Denver" },
  { value: "America/Phoenix", label: "US Arizona — Phoenix (no DST)" },
  { value: "America/Los_Angeles", label: "US Pacific — Los Angeles" },
  { value: "America/Anchorage", label: "US Alaska — Anchorage" },
  { value: "Pacific/Honolulu", label: "US Hawaii — Honolulu" },
  { value: "America/Puerto_Rico", label: "Puerto Rico" },
  { value: "America/Toronto", label: "Canada Eastern — Toronto" },
  { value: "America/Winnipeg", label: "Canada Central — Winnipeg" },
  { value: "America/Regina", label: "Canada — Saskatchewan (no DST)" },
  { value: "America/Edmonton", label: "Canada Mountain — Edmonton" },
  { value: "America/Vancouver", label: "Canada Pacific — Vancouver" },
  { value: "America/Halifax", label: "Canada Atlantic — Halifax" },
  { value: "Asia/Kolkata", label: "India — Kolkata" },
  { value: "Asia/Dubai", label: "UAE — Dubai" },
  { value: "Asia/Riyadh", label: "Saudi Arabia — Riyadh" },
  { value: "Asia/Qatar", label: "Qatar" },
  { value: "Asia/Kuwait", label: "Kuwait" },
  { value: "Asia/Muscat", label: "Oman — Muscat" },
  { value: "Asia/Bahrain", label: "Bahrain" },
  { value: "Asia/Karachi", label: "Pakistan — Karachi" },
  { value: "Asia/Dhaka", label: "Bangladesh — Dhaka" },
  { value: "Asia/Colombo", label: "Sri Lanka — Colombo" },
  { value: "Asia/Kathmandu", label: "Nepal — Kathmandu" },
  { value: "Asia/Singapore", label: "Singapore" },
  { value: "Asia/Kuala_Lumpur", label: "Malaysia — Kuala Lumpur" },
  { value: "Asia/Hong_Kong", label: "Hong Kong" },
  { value: "Asia/Shanghai", label: "China — Shanghai" },
  { value: "Asia/Tokyo", label: "Japan — Tokyo" },
  { value: "Australia/Sydney", label: "Australia Eastern — Sydney" },
  { value: "Australia/Perth", label: "Australia Western — Perth" },
  { value: "Pacific/Auckland", label: "New Zealand — Auckland" },
  { value: "Europe/London", label: "UK — London" },
  { value: "Europe/Dublin", label: "Ireland — Dublin" },
  { value: "Europe/Paris", label: "Central Europe — Paris" },
  { value: "Europe/Berlin", label: "Central Europe — Berlin" },
  { value: "Europe/Madrid", label: "Central Europe — Madrid" },
  { value: "Europe/Rome", label: "Central Europe — Rome" },
  { value: "Africa/Johannesburg", label: "South Africa — Johannesburg" },
  { value: "Africa/Lagos", label: "Nigeria — Lagos" },
  { value: "Africa/Nairobi", label: "Kenya — Nairobi" },
];
