import { Dimensions } from 'react-native';
import * as ScreenOrientation from 'expo-screen-orientation';

import { isTabletSize } from '@/lib/responsive';

/**
 * Rotation policy: **tablets rotate freely, phones stay portrait.**
 *
 * The native projects are unlocked (`app.json: orientation: "default"`), because
 * neither platform can express "tablets only" declaratively in a way that
 * survives a prebuild:
 *
 * - **iOS can**, via `UISupportedInterfaceOrientations~ipad` in `ios.infoPlist`,
 *   and does — so on iOS this call is a no-op reinforcing what the plist already
 *   says, and an iPhone never even flashes landscape.
 * - **Android cannot.** `android:screenOrientation` is a manifest enum with no
 *   `sw600dp` resource variant, so the only per-device options are patching
 *   `MainActivity` (regenerated by every prebuild) or locking at runtime. Hence
 *   this.
 *
 * Measuring the *screen's* short side rather than the window's width is what
 * makes the check work on a device that is already being held in landscape at
 * launch — see `@/lib/responsive`.
 *
 * One caveat worth not rediscovering: expo-screen-orientation's docs say
 * `lockAsync` is unreliable on iPad unless `requireFullScreen: true`, because a
 * multitasking-capable iPad reports itself as landscape. That does not bite here
 * — the only thing this ever asks an iPad to do is *unlock*, and `Info.plist`
 * keeps `UIRequiresFullScreen` false on purpose so Split View and Slide Over
 * keep working. Do not "fix" this by turning requireFullScreen on; it would
 * trade tablet multitasking for a lock we never take.
 */
export async function applyOrientationPolicy(): Promise<void> {
  const { width, height } = Dimensions.get('screen');
  if (isTabletSize(width, height)) {
    // Explicit rather than implicit: a previous session's lock persists on
    // Android, so a build that once locked portrait would stay locked.
    await ScreenOrientation.unlockAsync();
    return;
  }
  await ScreenOrientation.lockAsync(ScreenOrientation.OrientationLock.PORTRAIT_UP);
}
